### ISSUE TITLE
Bug whitelist_name in prune filter?

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-prune#1]
(This issue was originally filed by @alejgamez at https://github.com/elastic/logstash/issues/2253)

---

Hi everyone,

 I have a problem with the whitelist of prune filter, I don't know if this filter has some bug . I want to insert some fields in Elasticsearch and the logstash insert more fields. 

Thanks

**Comment by magnusbaeck** [comment]
@alejgamez, could you please provide additional details (including an example that exhibits the problem)? The current description is far too vague to act on.

**Comment by magnusbaeck** [comment]
Nothing to go on and no response to clarification request after a few months—closing issue.
