### ISSUE TITLE
Fix and enable specs

### ISSUE THREAD

**Issue by magnusbaeck** [logstash-plugins/logstash-filter-prune#11]
The specs are currently disabled:

``` ruby
# Currently the prune filter has bugs and I can't really tell what the intended
# behavior is.
#
# See the 'whitelist field values with interpolation' test for a commented
# explanation of my confusion.
describe LogStash::Filters::Prune, :if => false  do
```

The open questions need to be sorted out so that the specs can be reenabled.

The specs are actually working, but @jordansissel thought they were weird and ambiguous which is probably why they were disabled. This happened in before the plugins were split into their own gits and I haven't git blame'd the original code.

**Comment by jsvd** [comment]
@magnusbaeck I created https://github.com/logstash-plugins/logstash-filter-prune/pull/27 that will be able to close this issue, let me know what you think
