### ISSUE TITLE
Documentation unclear: prune affects tags?

### ISSUE THREAD

**Issue by 3ygun** [logstash-plugins/logstash-filter-prune#13]
## Problem

Prune's `whitelist_names` and `blacklist_names` affect tags (found it out after an hour). However the current documentation doesn't make that clear:
![whitelist current docs](https://cloud.githubusercontent.com/assets/5482320/17496430/156840ee-5d72-11e6-86b6-3cedb0fe972a.PNG)
## Version
- Ubuntu 16.04
- Logstash 2.3.3
- Logstash-filter-prune 2.0.5
## Example

Test case is: `{"test":{"bar":"6 1"},"hi":"hello"}`

Logstash.conf:

```
input {
  stdin {
    codec => json
  }
}

filter {
  # {"test":{"bar":"6 1"},"hi":"hello"}
  mutate { add_tag => [ "test_before" ] }
  prune  { whitelist_names =>  [ "^hi$" ] }
  mutate { add_tag => [ "test_after"]}
}

output {
  stdout { codec => rubydebug { metadata => true } }
}
```

Example output:
![prune a tag](https://cloud.githubusercontent.com/assets/5482320/17496349/bd5b4f86-5d71-11e6-8b17-722aa50e8a8a.PNG)

**Comment by 3ygun** [comment]
## Update

Because `add_tag` simply places the **_tags**_ in a field called `tags` prune's documentation of: **_include/exclude fields**_ makes more sense. However, it's still a confusing as they seem "separate" based on the difference in creation/deletion: `add_tag` vs `add_field` and `remove_tag` vs `remove_field`

**Comment by magnusbaeck** [comment]
Yeah, the fact that tags are really just strings in an array field but treated specially in _some_ cases is a bit of a problem. Maybe this plugin should be changed to skip tags when pruning, but that's obviously a breaking change. For now clarifying the documentation will do.

**Comment by magnusbaeck** [comment]
Closing now that #14 has been merged.
