### ISSUE TITLE
dependency setting in rubygems.org

### ISSUE THREAD

**Issue by lanejlanej** [logstash-plugins/logstash-filter-prune#16]
On rubygems.org the logstash-filter-prune v. 2.0.5 plugin has dependency logstash-core-plugin-api ~> 1.0
Is that right?

**Comment by magnusbaeck** [comment]
Well, as long as the plugin hasn't been adapted to the new event API it's correct. Unfortunately it's not completely trivial to update to the new API; see discussion in #12.
