### ISSUE TITLE
Prune interpolate causes exception when blacklist is omitted.

### ISSUE THREAD

**Issue by nicholasmoller** [logstash-plugins/logstash-filter-prune#24]
When using the prune filter's whitelist option and the `interpolate => true` option a fatal exception is produced:

``org.logstash.FieldReference$IllegalSyntaxException: Invalid FieldReference: `[^` ``

Seemingly caused by blacklist_fields default value being "%{[^}]+}" and a sprintf call that ultimately causes the error. Badger on the elastic forums pointed this out: https://discuss.elastic.co/t/prune-not-parsing-date-component-of-custom-elasticsearch-index/197129/2

**Config File**
```
input {
        beats {
                port => 5044
                ssl => true
                ssl_certificate_authorities => ["/etc/ssl/certs/ca_cert.pem"]
                ssl_certificate => "/etc/logstash/ssl/certs/logstash.pem"
                ssl_key => "/etc/logstash/ssl/keys/logstash-pkcs8.key"
                ssl_verify_mode => "force_peer"
        }
}

filter {
        prune {
                interpolate => true
                whitelist_names => ["message"]
        }
}

output {
        elasticsearch {
                hosts => ["http://localhost:9200"]
                index => "custom_index-%{+YYYY.MM.dd}"
                user => "username"
                password => "password"
        }
}
```
- Logstash Version: 7.3.1
- Operating System: Ubuntu 18.04.2 LTS
- Debug trace from console: https://pastebin.com/hx01S1kS

**Comment by jsvd** [comment]
closed by #25
