### ISSUE TITLE
Can not get the prune plugin to work.

### ISSUE THREAD

**Issue by kimvu3010** [logstash-plugins/logstash-filter-prune#26]
Hi, 
Im trying to delete field if its value = "N_A"; and I want this filter to run through all fields in the message, so i writing this in pipeline, but it's not working, the field with N_A values still exist in my kibana.

`	prune {
                blacklist_values => {"." => "^N_A$"}
       }`

I dont know where I am doing wrong. Maybe this issue a little bit too basic but I am just a newbie to this.
Please help, thank you.

**Comment by magnusbaeck** [comment]
As the template text for new issues says:

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

So, please post your question there and make sure you include additional details (like what your input event looks like). I'm closing this issue.

That said, I don't understand what your intention is with the period in `{"." => "^N_A$"}`. The key in the hash is supposed to be a fieldname and you hardly have a field named ".".
