### ISSUE TITLE
Will prune '@' fields if not in whitelist!

### ISSUE THREAD

**Issue by buddyp450** [logstash-plugins/logstash-filter-prune#4]
Hahaha, I really didn't expect this behavior as the fields prefaced by an @ sign are quasi-protected. Might want to add a note somewhere... if I get time I'll submit a PR.

**Comment by magnusbaeck** [comment]
Sorry about the slow response. There is no stated protection of @-prefixed fields so in a way I don't see the behavior as undesirable, but I do recognize that it in most cases won't be what the user expects.

I'd prefer if we could solve this with a configurable exception list that overrides any previous removal decision. With the current configuration interface I don't see how it's possible to even express "delete all fields matching some condition _except_ @-prefixed fields".

I'm assuming this'll be a backwards incompatible change, which would require a major version bump.

**Comment by buddyp450** [comment]
The only "real" issue with this is the common usage of Logstash with
elasticsearch which uses the protected @timestamp field. It has @version as
well but these were trivial to add to the whitelist.

**Comment by magnusbaeck** [comment]
Again, I don't agree that `@timestamp` is protected. Deleting the value is totally possible and sometimes useful.

**Comment by buddyp450** [comment]
Agree with you in retrospect and not worth changing for something so easily worked around.
